# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_registro.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 354)
        MainWindow.setWindowIcon(QtGui.QIcon("estilos/dark_icons/icon.png"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_registro = QtWidgets.QLabel(self.centralwidget)
        self.lbl_registro.setGeometry(QtCore.QRect(275, 28, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.lbl_registro.setFont(font)
        self.lbl_registro.setObjectName("lbl_registro")
        self.txt_editorial = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_editorial.setGeometry(QtCore.QRect(347, 155, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_editorial.setFont(font)
        self.txt_editorial.setObjectName("txt_editorial")
        self.txt_titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_titulo.setGeometry(QtCore.QRect(347, 83, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_titulo.setFont(font)
        self.txt_titulo.setObjectName("txt_titulo")
        self.lbl_genero = QtWidgets.QLabel(self.centralwidget)
        self.lbl_genero.setGeometry(QtCore.QRect(276, 190, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_genero.setFont(font)
        self.lbl_genero.setObjectName("lbl_genero")
        self.lbl_paginas = QtWidgets.QLabel(self.centralwidget)
        self.lbl_paginas.setGeometry(QtCore.QRect(507, 190, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_paginas.setFont(font)
        self.lbl_paginas.setObjectName("lbl_paginas")
        self.txt_autor = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_autor.setGeometry(QtCore.QRect(347, 119, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_autor.setFont(font)
        self.txt_autor.setObjectName("txt_autor")
        self.lbl_autor = QtWidgets.QLabel(self.centralwidget)
        self.lbl_autor.setGeometry(QtCore.QRect(276, 119, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_autor.setFont(font)
        self.lbl_autor.setObjectName("lbl_autor")
        self.lbl_titulo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_titulo.setGeometry(QtCore.QRect(276, 83, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lbl_editorial = QtWidgets.QLabel(self.centralwidget)
        self.lbl_editorial.setGeometry(QtCore.QRect(276, 155, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_editorial.setFont(font)
        self.lbl_editorial.setObjectName("lbl_editorial")
        self.btn_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_registrar.setGeometry(QtCore.QRect(277, 242, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.btn_registrar.setFont(font)
        self.btn_registrar.setObjectName("btn_registrar")
        self.txt_genero = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_genero.setGeometry(QtCore.QRect(347, 190, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_genero.setFont(font)
        self.txt_genero.setObjectName("txt_genero")
        self.txt_paginas = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_paginas.setGeometry(QtCore.QRect(577, 190, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_paginas.setFont(font)
        self.txt_paginas.setObjectName("txt_paginas")
        self.grv_registro = QtWidgets.QGraphicsView(self.centralwidget)
        self.grv_registro.setGeometry(QtCore.QRect(0, -20, 231, 381))
        self.grv_registro.setStyleSheet("*{background-image: url(\"estilos/batman.png\");}")
        self.grv_registro.setObjectName("grv_registro")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txt_titulo, self.txt_autor)
        MainWindow.setTabOrder(self.txt_autor, self.txt_editorial)
        MainWindow.setTabOrder(self.txt_editorial, self.txt_genero)
        MainWindow.setTabOrder(self.txt_genero, self.txt_paginas)
        MainWindow.setTabOrder(self.txt_paginas, self.btn_registrar)
        MainWindow.setTabOrder(self.btn_registrar, self.grv_registro)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " GESTOR COMICS - Registro"))
        self.lbl_registro.setText(_translate("MainWindow", "Datos registro nuevo Comic:"))
        self.lbl_genero.setText(_translate("MainWindow", "Género:"))
        self.lbl_paginas.setText(_translate("MainWindow", "Páginas:"))
        self.lbl_autor.setText(_translate("MainWindow", "Autor:"))
        self.lbl_titulo.setText(_translate("MainWindow", "Título:"))
        self.lbl_editorial.setText(_translate("MainWindow", "Editorial:"))
        self.btn_registrar.setText(_translate("MainWindow", "Registrar Comic"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
