# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_ficha_comic.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 243)
        MainWindow.setWindowIcon(QtGui.QIcon("estilos/dark_icons/window_icon.png"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_editorial = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_editorial.setEnabled(True)
        self.txt_editorial.setGeometry(QtCore.QRect(237, 94, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_editorial.setFont(font)
        self.txt_editorial.setStyleSheet("")
        self.txt_editorial.setReadOnly(True)
        self.txt_editorial.setObjectName("txt_editorial")
        self.txt_titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_titulo.setEnabled(True)
        self.txt_titulo.setGeometry(QtCore.QRect(237, 24, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_titulo.setFont(font)
        self.txt_titulo.setStyleSheet("")
        self.txt_titulo.setReadOnly(True)
        self.txt_titulo.setObjectName("txt_titulo")
        self.lbl_genero = QtWidgets.QLabel(self.centralwidget)
        self.lbl_genero.setGeometry(QtCore.QRect(168, 129, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_genero.setFont(font)
        self.lbl_genero.setObjectName("lbl_genero")
        self.lbl_paginas = QtWidgets.QLabel(self.centralwidget)
        self.lbl_paginas.setGeometry(QtCore.QRect(168, 164, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_paginas.setFont(font)
        self.lbl_paginas.setObjectName("lbl_paginas")
        self.txt_autor = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_autor.setEnabled(True)
        self.txt_autor.setGeometry(QtCore.QRect(237, 59, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_autor.setFont(font)
        self.txt_autor.setStyleSheet("")
        self.txt_autor.setReadOnly(True)
        self.txt_autor.setObjectName("txt_autor")
        self.lbl_autor = QtWidgets.QLabel(self.centralwidget)
        self.lbl_autor.setGeometry(QtCore.QRect(168, 59, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_autor.setFont(font)
        self.lbl_autor.setObjectName("lbl_autor")
        self.lbl_titulo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_titulo.setGeometry(QtCore.QRect(168, 24, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lbl_editorial = QtWidgets.QLabel(self.centralwidget)
        self.lbl_editorial.setGeometry(QtCore.QRect(168, 94, 63, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_editorial.setFont(font)
        self.lbl_editorial.setObjectName("lbl_editorial")
        self.btn_editar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_editar.setGeometry(QtCore.QRect(309, 200, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.btn_editar.setFont(font)
        self.btn_editar.setObjectName("btn_editar")
        self.lbl_tapa = QtWidgets.QLabel(self.centralwidget)
        self.lbl_tapa.setGeometry(QtCore.QRect(390, 129, 44, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_tapa.setFont(font)
        self.lbl_tapa.setObjectName("lbl_tapa")
        self.lbl_imagen = QtWidgets.QLabel(self.centralwidget)
        self.lbl_imagen.setGeometry(QtCore.QRect(22, 20, 134, 202))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.lbl_imagen.setFont(font)
        self.lbl_imagen.setStyleSheet("*{background-color: transparent; border:1px solid #32414B;}")
        self.lbl_imagen.setText("")
        self.lbl_imagen.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_imagen.setObjectName("lbl_imagen")
        self.txt_genero = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_genero.setEnabled(True)
        self.txt_genero.setGeometry(QtCore.QRect(237, 129, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_genero.setFont(font)
        self.txt_genero.setStyleSheet("")
        self.txt_genero.setReadOnly(True)
        self.txt_genero.setObjectName("txt_genero")
        self.txt_paginas = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_paginas.setEnabled(True)
        self.txt_paginas.setGeometry(QtCore.QRect(237, 164, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_paginas.setFont(font)
        self.txt_paginas.setStyleSheet("")
        self.txt_paginas.setReadOnly(True)
        self.txt_paginas.setObjectName("txt_paginas")
        self.txt_tapa = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_tapa.setEnabled(True)
        self.txt_tapa.setGeometry(QtCore.QRect(440, 129, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_tapa.setFont(font)
        self.txt_tapa.setStyleSheet("")
        self.txt_tapa.setReadOnly(True)
        self.txt_tapa.setObjectName("txt_tapa")
        self.lbl_coleccion = QtWidgets.QLabel(self.centralwidget)
        self.lbl_coleccion.setGeometry(QtCore.QRect(310, 164, 160, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_coleccion.setFont(font)
        self.lbl_coleccion.setObjectName("lbl_coleccion")
        self.txt_coleccion = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_coleccion.setEnabled(True)
        self.txt_coleccion.setGeometry(QtCore.QRect(478, 164, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_coleccion.setFont(font)
        self.txt_coleccion.setStyleSheet("")
        self.txt_coleccion.setReadOnly(True)
        self.txt_coleccion.setObjectName("txt_coleccion")
        self.btn_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guardar.setGeometry(QtCore.QRect(420, 200, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.btn_guardar.setFont(font)
        self.btn_guardar.setObjectName("btn_guardar")
        self.lbl_sin_portada = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sin_portada.setGeometry(QtCore.QRect(24, 98, 130, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.lbl_sin_portada.setFont(font)
        self.lbl_sin_portada.setStyleSheet("")
        self.lbl_sin_portada.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sin_portada.setObjectName("lbl_sin_portada")
        self.btn_editar_portada = QtWidgets.QPushButton(self.centralwidget)
        self.btn_editar_portada.setGeometry(QtCore.QRect(44, 110, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.btn_editar_portada.setFont(font)
        self.btn_editar_portada.setStyleSheet("*{color: yellow;}")
        self.btn_editar_portada.setObjectName("btn_editar_portada")
        self.btn_cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancelar.setGeometry(QtCore.QRect(309, 200, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.btn_cancelar.setFont(font)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.btn_cerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cerrar.setGeometry(QtCore.QRect(420, 200, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.btn_cerrar.setFont(font)
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.lbl_sin_portada.raise_()
        self.txt_editorial.raise_()
        self.txt_titulo.raise_()
        self.lbl_genero.raise_()
        self.lbl_paginas.raise_()
        self.txt_autor.raise_()
        self.lbl_autor.raise_()
        self.lbl_titulo.raise_()
        self.lbl_editorial.raise_()
        self.btn_editar.raise_()
        self.lbl_tapa.raise_()
        self.lbl_imagen.raise_()
        self.txt_genero.raise_()
        self.txt_paginas.raise_()
        self.txt_tapa.raise_()
        self.lbl_coleccion.raise_()
        self.txt_coleccion.raise_()
        self.btn_guardar.raise_()
        self.btn_editar_portada.raise_()
        self.btn_cancelar.raise_()
        self.btn_cerrar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txt_titulo, self.txt_autor)
        MainWindow.setTabOrder(self.txt_autor, self.txt_editorial)
        MainWindow.setTabOrder(self.txt_editorial, self.txt_genero)
        MainWindow.setTabOrder(self.txt_genero, self.txt_tapa)
        MainWindow.setTabOrder(self.txt_tapa, self.txt_paginas)
        MainWindow.setTabOrder(self.txt_paginas, self.txt_coleccion)
        MainWindow.setTabOrder(self.txt_coleccion, self.btn_editar)
        MainWindow.setTabOrder(self.btn_editar, self.btn_cancelar)
        MainWindow.setTabOrder(self.btn_cancelar, self.btn_guardar)
        MainWindow.setTabOrder(self.btn_guardar, self.btn_editar_portada)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " GESTOR COMICS - Ficha cómic"))
        self.txt_editorial.setPlaceholderText(_translate("MainWindow", "Sin dato"))
        self.lbl_genero.setText(_translate("MainWindow", "Género:"))
        self.lbl_paginas.setText(_translate("MainWindow", "Páginas:"))
        self.txt_autor.setPlaceholderText(_translate("MainWindow", "Sin dato"))
        self.lbl_autor.setText(_translate("MainWindow", "Autor:"))
        self.lbl_titulo.setText(_translate("MainWindow", "Título:"))
        self.lbl_editorial.setText(_translate("MainWindow", "Editorial:"))
        self.btn_editar.setText(_translate("MainWindow", "Editar"))
        self.lbl_tapa.setText(_translate("MainWindow", "Tapa:"))
        self.txt_genero.setPlaceholderText(_translate("MainWindow", "Sin dato"))
        self.txt_tapa.setPlaceholderText(_translate("MainWindow", "Sin dato"))
        self.lbl_coleccion.setText(_translate("MainWindow", "Pertenece a colección:"))
        self.btn_guardar.setText(_translate("MainWindow", "Guardar"))
        self.lbl_sin_portada.setText(_translate("MainWindow", "Sin portada"))
        self.btn_editar_portada.setText(_translate("MainWindow", "Editar"))
        self.btn_cancelar.setText(_translate("MainWindow", "Cancelar"))
        self.btn_cerrar.setText(_translate("MainWindow", "Cerrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
