# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_registro.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 354)
        MainWindow.setWindowIcon(QtGui.QIcon("estilos/dark_icons/window_icon.png"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_registro = QtWidgets.QLabel(self.centralwidget)
        self.lbl_registro.setGeometry(QtCore.QRect(271, 11, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.lbl_registro.setFont(font)
        self.lbl_registro.setObjectName("lbl_registro")
        self.txt_editorial = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_editorial.setGeometry(QtCore.QRect(343, 124, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_editorial.setFont(font)
        self.txt_editorial.setObjectName("txt_editorial")
        self.txt_titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_titulo.setGeometry(QtCore.QRect(343, 54, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_titulo.setFont(font)
        self.txt_titulo.setObjectName("txt_titulo")
        self.lbl_genero = QtWidgets.QLabel(self.centralwidget)
        self.lbl_genero.setGeometry(QtCore.QRect(272, 159, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_genero.setFont(font)
        self.lbl_genero.setObjectName("lbl_genero")
        self.lbl_paginas = QtWidgets.QLabel(self.centralwidget)
        self.lbl_paginas.setGeometry(QtCore.QRect(494, 159, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_paginas.setFont(font)
        self.lbl_paginas.setObjectName("lbl_paginas")
        self.txt_autor = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_autor.setGeometry(QtCore.QRect(343, 89, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.txt_autor.setFont(font)
        self.txt_autor.setObjectName("txt_autor")
        self.lbl_autor = QtWidgets.QLabel(self.centralwidget)
        self.lbl_autor.setGeometry(QtCore.QRect(272, 89, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_autor.setFont(font)
        self.lbl_autor.setObjectName("lbl_autor")
        self.lbl_titulo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_titulo.setGeometry(QtCore.QRect(272, 54, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lbl_editorial = QtWidgets.QLabel(self.centralwidget)
        self.lbl_editorial.setGeometry(QtCore.QRect(272, 124, 63, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_editorial.setFont(font)
        self.lbl_editorial.setObjectName("lbl_editorial")
        self.btn_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_registrar.setGeometry(QtCore.QRect(274, 265, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.btn_registrar.setFont(font)
        self.btn_registrar.setObjectName("btn_registrar")
        self.lbl_portada = QtWidgets.QLabel(self.centralwidget)
        self.lbl_portada.setGeometry(QtCore.QRect(272, 194, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_portada.setFont(font)
        self.lbl_portada.setObjectName("lbl_portada")
        self.btn_imagen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_imagen.setGeometry(QtCore.QRect(390, 193, 224, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_imagen.setFont(font)
        self.btn_imagen.setToolTip("")
        self.btn_imagen.setToolTipDuration(-1)
        self.btn_imagen.setObjectName("btn_imagen")
        self.cmb_genero = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_genero.setGeometry(QtCore.QRect(343, 159, 141, 22))
        self.cmb_genero.setObjectName("cmb_genero")
        self.cmb_genero.addItem("")
        self.cmb_genero.setItemText(0, "")
        self.cmb_genero.addItem("")
        self.cmb_genero.addItem("")
        self.cmb_genero.addItem("")
        self.cmb_genero.addItem("")
        self.cmb_genero.addItem("")
        self.cmb_genero.addItem("")
        self.lbl_tapa = QtWidgets.QLabel(self.centralwidget)
        self.lbl_tapa.setGeometry(QtCore.QRect(272, 229, 44, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lbl_tapa.setFont(font)
        self.lbl_tapa.setObjectName("lbl_tapa")
        self.rdb_blanda = QtWidgets.QRadioButton(self.centralwidget)
        self.rdb_blanda.setGeometry(QtCore.QRect(326, 230, 69, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.rdb_blanda.setFont(font)
        self.rdb_blanda.setChecked(True)
        self.rdb_blanda.setObjectName("rdb_blanda")
        self.rdb_cartone = QtWidgets.QRadioButton(self.centralwidget)
        self.rdb_cartone.setGeometry(QtCore.QRect(401, 230, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.rdb_cartone.setFont(font)
        self.rdb_cartone.setObjectName("rdb_cartone")
        self.spb_paginas = QtWidgets.QSpinBox(self.centralwidget)
        self.spb_paginas.setGeometry(QtCore.QRect(562, 159, 52, 22))
        self.spb_paginas.setMaximum(9999)
        self.spb_paginas.setObjectName("spb_paginas")
        self.chb_coleccion = QtWidgets.QCheckBox(self.centralwidget)
        self.chb_coleccion.setGeometry(QtCore.QRect(520, 230, 91, 18))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.chb_coleccion.setFont(font)
        self.chb_coleccion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chb_coleccion.setObjectName("chb_coleccion")
        self.lbl_imagen = QtWidgets.QLabel(self.centralwidget)
        self.lbl_imagen.setGeometry(QtCore.QRect(0, -20, 231, 381))
        self.lbl_imagen.setStyleSheet("*{background-image: url(\"estilos/batman.png\"); border:1px solid #32414B;}")
        self.lbl_imagen.setText("")
        self.lbl_imagen.setObjectName("lbl_imagen")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txt_titulo, self.txt_autor)
        MainWindow.setTabOrder(self.txt_autor, self.txt_editorial)
        MainWindow.setTabOrder(self.txt_editorial, self.cmb_genero)
        MainWindow.setTabOrder(self.cmb_genero, self.spb_paginas)
        MainWindow.setTabOrder(self.spb_paginas, self.btn_imagen)
        MainWindow.setTabOrder(self.btn_imagen, self.rdb_blanda)
        MainWindow.setTabOrder(self.rdb_blanda, self.rdb_cartone)
        MainWindow.setTabOrder(self.rdb_cartone, self.chb_coleccion)
        MainWindow.setTabOrder(self.chb_coleccion, self.btn_registrar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " GESTOR COMICS - Registro"))
        self.lbl_registro.setText(_translate("MainWindow", "Registro nuevo cómic:"))
        self.lbl_genero.setText(_translate("MainWindow", "Género:"))
        self.lbl_paginas.setText(_translate("MainWindow", "Páginas:"))
        self.lbl_autor.setText(_translate("MainWindow", "Autor:"))
        self.lbl_titulo.setText(_translate("MainWindow", "Título:"))
        self.lbl_editorial.setText(_translate("MainWindow", "Editorial:"))
        self.btn_registrar.setText(_translate("MainWindow", "Registrar Cómic"))
        self.lbl_portada.setText(_translate("MainWindow", "Portada cómic:"))
        self.btn_imagen.setText(_translate("MainWindow", "Seleccionar imagen"))
        self.cmb_genero.setItemText(1, _translate("MainWindow", "Superhéroes"))
        self.cmb_genero.setItemText(2, _translate("MainWindow", "Ciencia ficción"))
        self.cmb_genero.setItemText(3, _translate("MainWindow", "Histórico"))
        self.cmb_genero.setItemText(4, _translate("MainWindow", "Alternativo"))
        self.cmb_genero.setItemText(5, _translate("MainWindow", "Europeo"))
        self.cmb_genero.setItemText(6, _translate("MainWindow", "Otros"))
        self.lbl_tapa.setText(_translate("MainWindow", "Tapa:"))
        self.rdb_blanda.setText(_translate("MainWindow", "Blanda"))
        self.rdb_cartone.setText(_translate("MainWindow", "Dura"))
        self.chb_coleccion.setText(_translate("MainWindow", " Colección"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
