# Generated by Django 3.0.5 on 2020-05-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('clave', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=2000)),
                ('horario', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=150)),
                ('emailvalido', models.CharField(max_length=150)),
                ('precio', models.FloatField(default=0)),
                ('tfno', models.CharField(max_length=2)),
                ('mail', models.CharField(max_length=2)),
                ('codigo', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partdapp.Categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partdapp.Usuarios')),
            ],
        ),
    ]
