# Generated by Django 3.0.5 on 2020-05-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partdapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('mensaje', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='foto',
            field=models.ImageField(default='images/noperfil.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='emailvalido',
            field=models.CharField(default='SI', max_length=150),
        ),
    ]
