# Generated by Django 3.0.5 on 2020-05-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partdapp', '0002_auto_20200511_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='foto',
            field=models.ImageField(default='partdapp/static/images/noperfil.png', upload_to='partdapp/static/images'),
        ),
    ]
