# Generated by Django 3.0.5 on 2020-05-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partdapp', '0003_auto_20200511_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='foto',
            field=models.ImageField(default='images/noperfil.png', upload_to='images'),
        ),
    ]
