# Generated by Django 3.0.5 on 2020-05-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partdapp', '0004_auto_20200511_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='emailvalido',
            field=models.CharField(default='NO', max_length=150),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='foto',
            field=models.ImageField(default='images/profile/noperfil.png', upload_to='images/profile'),
        ),
    ]
