# Generated by Django 2.2.7 on 2020-05-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partdapp', '0005_auto_20200512_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='codigo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
